application:
    api:
        rootPath: /api
        swagger:
            path: /api-docs/swagger
            version: 3.19.4
            layout: StandaloneLayout
            deepLinking: true

micronaut:
    application:
        name: ubw-rest
        instance: ${random.uuid}
        version: 0.1
    server:
        port: 9090
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: ${application.api.swagger.path}/**
    views:
        handlebars:
            enabled: true
            #extension: mustache
