application:
    api:
        swagger:
            path: /api-docs/swagger
            version: 3.19.4
            layout: StandaloneLayout
            deepLinking: true
            urls:
            - name: swagger-server
              url: /api-docs/swagger/swagger-server-0.1.yml
            #- name: spec2
            #  url: url2

micronaut:
    application:
        name: swagger-server
        instance: ${random.uuid}
        version: 0.1
#    server:
#        port: 9090
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: ${application.api.swagger.path}/**

    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true

endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
        url:
            enabled: true
