application:
    api:
        swagger:
            path: /api-docs/swagger
            version: 3.19.4
            layout: StandaloneLayout
            deepLinking: true
            urls:
            - name: ubw-rest
              url: /api-docs/swagger/ubw-rest-0.1.yml
            #- name: spec2
            #  url: url2

micronaut:
    application:
        name: ubw-rest
        instance: ${random.uuid}
        version: 0.1
    server:
        port: 9090
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: ${application.api.swagger.path}/**
    views:
        handlebars:
            enabled: true
            #extension: mustache
